### ISSUE TITLE
可以更新一下吗

### ISSUE THREAD

**Issue by huajii** [qinlili23333/ctfile.TencentCloud#1]
cloudflare太慢了 能不能把源码更新一下

**Comment by qinlili23333** [comment]
腾讯云现在第四个月开始就没有免费额度了，由于没有人每个月赞助我9.9元维持最低的资源包，我没有继续更新源码的条件了
cloudflare仍然是免费的，所以我可以持续维护更新。如果需要更快的速度，建议购买企业版cloudflare套餐
如果有人给我打钱，我会考虑继续更新腾讯云版本的源码
![image](https://user-images.githubusercontent.com/24567775/165422551-142fce51-535a-4d41-b37a-a31ea206c6cd.png)
